services:
  app:
    container_name: python-read-files-api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - 8012:8012
    volumes:
      - ../:/home/app
    networks:
      - app_network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_gaulke_contabil

    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-db:

networks:
  app_network:
    external: true
